wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710696856.0
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.11.3
      5: 0.16.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
activations:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 32
beta_value:
  desc: null
  value: 0.9
epochs:
  desc: null
  value: 15
initialization:
  desc: null
  value: xavier
learning_rate:
  desc: null
  value: 0.0001
loss_type:
  desc: null
  value: cross_entropy
neurons_in_hidden_layers:
  desc: null
  value: 128
number_of_hidden_layers:
  desc: null
  value: 3
optimizers:
  desc: null
  value: nadam
weight_decay:
  desc: null
  value: 0
